/* Generated by generate_assets.cpp - DO NOT EDIT */
#ifndef __BIN_ASSETS_H__
#define __BIN_ASSETS_H__

#include <cstdint>
#include <cstddef>

/* Asset: exp_board_images/buttons.png */
extern const uint8_t bin_asset_exp_board_images_buttons_png[];
extern const size_t bin_asset_exp_board_images_buttons_png_len;

/* Asset: exp_board_images/buzzers.png */
extern const uint8_t bin_asset_exp_board_images_buzzers_png[];
extern const size_t bin_asset_exp_board_images_buzzers_png_len;

/* Asset: exp_board_images/dips.png */
extern const uint8_t bin_asset_exp_board_images_dips_png[];
extern const size_t bin_asset_exp_board_images_dips_png_len;

/* Asset: exp_board_images/dpad.png */
extern const uint8_t bin_asset_exp_board_images_dpad_png[];
extern const size_t bin_asset_exp_board_images_dpad_png_len;

/* Asset: exp_board_images/edison.png */
extern const uint8_t bin_asset_exp_board_images_edison_png[];
extern const size_t bin_asset_exp_board_images_edison_png_len;

/* Asset: exp_board_images/fader.png */
extern const uint8_t bin_asset_exp_board_images_fader_png[];
extern const size_t bin_asset_exp_board_images_fader_png_len;

/* Asset: exp_board_images/fader_slot.png */
extern const uint8_t bin_asset_exp_board_images_fader_slot_png[];
extern const size_t bin_asset_exp_board_images_fader_slot_png_len;

/* Asset: exp_board_images/leds.png */
extern const uint8_t bin_asset_exp_board_images_leds_png[];
extern const size_t bin_asset_exp_board_images_leds_png_len;

/* Asset: exp_board_images/seven_segment.png */
extern const uint8_t bin_asset_exp_board_images_seven_segment_png[];
extern const size_t bin_asset_exp_board_images_seven_segment_png_len;

/* Asset: exp_board_images/teenyat_font.png */
extern const uint8_t bin_asset_exp_board_images_teenyat_font_png[];
extern const size_t bin_asset_exp_board_images_teenyat_font_png_len;

#endif /* __BIN_ASSETS_H__ */
